frontend_task:
  description: >
    Write a streamlit UI in a module app.py that demonstrates the given backend 
    class in {module_name} which can be found in output/src/{module_name}.py.
    Assume there is only 1 user, and keep the UI very simple indeed - just a prototype or demo.
    Here are the requirements: {requirements}
  expected_output: >
    A streamlit UI in module app.py that demonstrates the given backend class.
    The file should be ready so that it can be run as-is, in the same directory
     as the backend module, and it should import the backend class from 
     {module_name}.

    IMPORTANT: Output ONLY the raw Python code without any markdown formatting, 
    code block delimiters, or backticks. The output should be valid Python code 
    that can be directly saved to a file and executed.
  agent: frontend_engineer
  output_file: output/app.py