design_task:
  description: >
    Take the high level requirements described here and prepare a detailed design for the engineer

    Requirements: {requirements}

    Architecture Standards: {architecture_standards}

    IMPORTANT: Only output the design in markdown format, laying out the detail for any required
    modules, classes, functions, and methods.
  expected_output: >
    A detailed design for the backend developer listing out every module, class, function, and method
  agent: engineering_lead
  output_file: output/design.md

task_creation_task:
  description: >
    Using the task creation tool, create a list of  tasks for the engineering team based on the design provided by the engineering lead.
    There should be a single task for each module that contains the classes, functions, and methods described in the design.
  expected_output: >
    A list of tasks assigned to each engineer, including the task description, the engineer assigned to it, and the deadline for completion.
    Use the list all tasks tool to create this output.
  agent: engineering_lead