design_task:
  description: >
    Take the high level requirements described here and prepare a detailed design for the engineer

    Requirements: {requirements}

    Architecture Standards: {architecture_standards}

    IMPORTANT: Use multiple modules arranged in a directory structure that organizes the code according
    to best practices.  The directory structure should be included in the design.

  expected_output: >
    A detailed design for the backend developer listing out every module, class, function, and method
  agent: software_architect

implement_backend_code_task:
  description: >
    Implement all modules required for the design provided by the software architect.
    You should use the file read and file writer tools to explore the source directlyr and make modifications
    to it.  All files should be read from and written to the {src_base_directory} directory.
  expected_output: >
    All tasks have been marked as complete and all source code has been written to the {src_base_directory} directory.
  agent: backend_developer
  context:
    - design_task

