design_task:
  description: >
    Take the high level requirements described here and prepare a detailed design for the engineer

    Requirements: {requirements}

    Architecture Standards: {architecture_standards}

    IMPORTANT: Only output the design in markdown format, laying out the detail for any required
    modules, classes, functions, and methods.
  expected_output: >
    A detailed design for the backend developer listing out every module, class, function, and method
  agent: engineering_lead
